
meta_title: "CashBack - Expense tracking in real-time"
meta_description: "Expense tracking in real-time"
meta_image: "diamond.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@cashback" # indispensable pour les Twitter Cards
